Enumeration/iteration day2
vanzeldsilva/ruby-example pull request #4
Opened 2021-09-27 12:43 UTC by vanzeldsilva

2021-09-27 16:12 UTC, ahmad19 requested changes
I have commented some thoughts. Take a look.

2021-09-27 16:12 UTC, ahmad19 commented on iteration/exercises/spec/inject_pattern_spec.rb
>      menu = {
I want you to do this on your own.

2021-09-28 17:00 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/any_pattern_spec.rb
> +    end
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/0a4a9984c33eec67cff10c92524c05f9c634b625#diff-2ed064813792b1ed30ba7da42eb94cbbf1dd97e643e6558277b87eff3c09d2ecR47

2021-09-28 17:01 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/map_pattern_spec.rb
> +    end
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/edf36be70a7b8b10fc7e516661ec7097a33f684b#diff-a3afdfc31842fd3619d5a1995f8e4fa6058d3b6beece285c1baefe828f0de323R73

2021-09-28 17:03 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/reduce_pattern_spec.rb
> +    phrase =
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/d967e3ce91aadc2fc8e2323bae30745afcfb5267#diff-aeae80d542d3dd35310add7aa775296c49fa79f03d7589f8770664601d2a8d72R35

2021-09-28 17:04 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/reduce_pattern_spec.rb
> +  it 'subtracts smallest numbers from 100' do
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/d967e3ce91aadc2fc8e2323bae30745afcfb5267#diff-aeae80d542d3dd35310add7aa775296c49fa79f03d7589f8770664601d2a8d72R59

2021-09-28 17:05 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/select_pattern_spec.rb
>      expect(arrays).to eq([["dog"], [56, 3, 8]])
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/b2950b302b2b1b67c73cfc44590616635c500786#diff-338f2ed81ee1aa4206990b80956d2e8e7dcb054e1d0279436955566c1726f308R95

2021-09-28 17:06 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/basic_enums_spec.rb
>      5.times do
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/41e4ceaf1b67c9e99daf644fa38f501b641751ce#diff-ac558eb8602b25b9a463ab290aa07b127c9e1b0f8cd71412a3c38f64b475e47eR5

2021-09-28 17:09 UTC, vanzeldsilva commented on iteration/exercises/spec/inject_pattern_spec.rb
>      menu = {
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/3abb8f7ae9f74b759b5747ae547b31dfa70e4cb0#diff-081abc5bade9588ba60ec100cac96c7796d4f852ea7eea8f957ec6a5756680caR103

2021-09-28 17:10 UTC, vanzeldsilva commented on iteration/exercises/spec/inject_pattern_spec.rb
> +    end
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/3abb8f7ae9f74b759b5747ae547b31dfa70e4cb0#diff-081abc5bade9588ba60ec100cac96c7796d4f852ea7eea8f957ec6a5756680caR103

2021-09-28 18:06 UTC, ahmad19 commented on enumerables/exercises_1/spec/one_pattern_spec.rb
> +      end
Here 

```
8.digits(2)
=> [0, 0, 0, 1]
```

```
333.digits(2)
=> [1, 0, 1, 1, 0, 0, 1, 0, 1]
```

`digits(2)` returns binary number which we dont need. 

What we need is the number of digits in a number. So for example: For integer 333, the number of digits are 3. Therefore:

```
numbers.each do |number|
  digits = num.digits
  count += 1 if  && digits.length > 1 && num < 3 
end
```

2021-09-28 18:07 UTC, ahmad19 commented on enumerables/exercises_1/spec/select_pattern_spec.rb
> +      floats << number if ('%.2f' % number)
I assume that you're still doing this one ?

2021-09-29 04:16 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/select_pattern_spec.rb
> +      floats << number if ('%.2f' % number)
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/b2950b302b2b1b67c73cfc44590616635c500786#diff-338f2ed81ee1aa4206990b80956d2e8e7dcb054e1d0279436955566c1726f308R87

2021-09-29 12:38 UTC, vanzeldsilva commented on iteration/exercises/spec/inject_pattern_spec.rb
>      menu = {
done - https://github.com/vanzeldsilva/ruby-example/pull/4/commits/6bc266d9e673e4df5a06ca874e82b78c391a6b2c#diff-081abc5bade9588ba60ec100cac96c7796d4f852ea7eea8f957ec6a5756680caR177

2021-10-12 05:59 UTC, vanzeldsilva commented on iteration/exercises/spec/inject_pattern_spec.rb
>      menu = {
https://github.com/vanzeldsilva/ruby-example/pull/4/commits/d4c0112eec83ef38e9376c00223fab5d1a99730b#diff-081abc5bade9588ba60ec100cac96c7796d4f852ea7eea8f957ec6a5756680caR179 - done

2021-10-12 06:00 UTC, vanzeldsilva commented on enumerables/exercises_1/spec/reject_pattern_spec.rb
> +      remaining << letter unless letter.()
https://github.com/vanzeldsilva/ruby-example/pull/4/commits/d4c0112eec83ef38e9376c00223fab5d1a99730b#diff-d22ac7bee355895bc1bddcfb07bf36ecd5f33e388fb685c270ff90b1a3565598R17 - done

2021-10-12 10:40 UTC, merged